# -*- coding: utf-8 -*-
"""CV and IP Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pCayOPzwA9SHqEoOf0kEq4xz57GsgGya
"""

!pip install -q opencv-python-headless numpy tqdm ultralytics kagglehub deep-sort-realtime pandas

import os
import cv2
import numpy as np
import pandas as pd
from tqdm import tqdm
from ultralytics import YOLO
import kagglehub
from deep_sort_realtime.deepsort_tracker import DeepSort

DATASET_PATH = kagglehub.dataset_download(
    "vafaeii/cdnet-2014-change-detection-benchmark-dataset"
)

DATASET_ROOT = os.path.join(DATASET_PATH, "dataset")
RESULTS_ROOT = "/content/results"

os.makedirs(RESULTS_ROOT, exist_ok=True)

print("Dataset downloaded at:", DATASET_PATH)

MIN_AREA = 200
ALLOWED_CLASSES = ["person"]
YOLO_CONF = 0.25

# YOLOv8
yolo_model = YOLO("yolov8s.pt")

# Background Subtraction (KNN)
bg_sub = cv2.createBackgroundSubtractorKNN(
    history=300,
    dist2Threshold=400,
    detectShadows=True
)

# DeepSORT Tracker
tracker = DeepSort(
    max_age=30,
    n_init=3,
    max_iou_distance=0.7
)

def read_temporal_roi(path):
    with open(path, "r") as f:
        start, end = map(int, f.read().split())
    return start, end


def load_roi(path, frame_shape):
    roi = cv2.imread(path, 0)
    roi = cv2.resize(
        roi,
        (frame_shape[1], frame_shape[0]),
        interpolation=cv2.INTER_NEAREST
    )
    return (roi > 0).astype("uint8") * 255


def preprocess_frame(frame, roi):
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    gray = cv2.GaussianBlur(gray, (5, 5), 0)
    return cv2.bitwise_and(gray, gray, mask=roi)


def remove_small_objects(mask, min_area=MIN_AREA):
    contours, _ = cv2.findContours(
        mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE
    )
    for cnt in contours:
        if cv2.contourArea(cnt) < min_area:
            cv2.drawContours(mask, [cnt], -1, 0, -1)
    return mask


def optical_flow_refine(prev_gray, curr_gray, fg_mask):
    if prev_gray is None:
        return fg_mask

    flow = cv2.calcOpticalFlowFarneback(
        prev_gray, curr_gray,
        None, 0.5, 3, 15, 3, 5, 1.2, 0
    )

    mag, _ = cv2.cartToPolar(flow[..., 0], flow[..., 1])
    motion_mask = (mag > 0.5).astype(np.uint8) * 255

    return cv2.bitwise_and(fg_mask, motion_mask)

def detect_persons(frame):
    results = yolo_model(frame, conf=YOLO_CONF, imgsz=640, verbose=False)[0]
    detections = []

    if results.boxes is not None:
        for box, cls, conf in zip(
            results.boxes.xyxy,
            results.boxes.cls,
            results.boxes.conf
        ):
            class_name = yolo_model.names[int(cls)]

            if class_name not in ALLOWED_CLASSES:
                continue

            x1, y1, x2, y2 = map(int, box)
            detections.append(
                ([x1, y1, x2 - x1, y2 - y1], conf.item(), "person")
            )

    return detections


def track_persons(frame):
    detections = detect_persons(frame)
    tracks = tracker.update_tracks(detections, frame=frame)
    return tracks


def fuse_motion_yolo(fg_mask, tracks, shape):
    yolo_mask = np.zeros(shape, dtype=np.uint8)

    for track in tracks:
        if not track.is_confirmed():
            continue

        l, t, r, b = map(int, track.to_ltrb())
        cv2.rectangle(yolo_mask, (l, t), (r, b), 255, -1)

    return cv2.bitwise_or(fg_mask, yolo_mask)

for category in os.listdir(DATASET_ROOT):

    category_path = os.path.join(DATASET_ROOT, category)
    if not os.path.isdir(category_path):
        continue

    print(f"\n📂 Processing category: {category}")

    for sequence in os.listdir(category_path):

        seq_path = os.path.join(category_path, sequence)
        input_dir = os.path.join(seq_path, "input")

        if not os.path.isdir(input_dir):
            continue

        print(f" ▶ Sequence: {sequence}")

        frame_files = sorted(os.listdir(input_dir))
        first_frame = cv2.imread(os.path.join(input_dir, frame_files[0]))

        roi = load_roi(os.path.join(seq_path, "ROI.bmp"), first_frame.shape)
        start_f, end_f = read_temporal_roi(
            os.path.join(seq_path, "temporalROI.txt")
        )

        output_dir = os.path.join(RESULTS_ROOT, category, sequence)
        os.makedirs(output_dir, exist_ok=True)

        prev_gray = None

        for idx, fname in enumerate(tqdm(frame_files, leave=False)):

            frame_id = idx + 1

            if frame_id < start_f or frame_id > end_f:
                continue

            frame = cv2.imread(os.path.join(input_dir, fname))
            processed = preprocess_frame(frame, roi)

            fg = bg_sub.apply(processed)
            fg[fg == 127] = 0

            fg = optical_flow_refine(prev_gray, processed, fg)
            prev_gray = processed.copy()

            kernel = cv2.getStructuringElement(
                cv2.MORPH_ELLIPSE, (3, 3)
            )

            fg = cv2.morphologyEx(fg, cv2.MORPH_OPEN, kernel)
            fg = cv2.morphologyEx(fg, cv2.MORPH_CLOSE, kernel)

            fg = remove_small_objects(fg)

            tracks = track_persons(frame)
            fg = fuse_motion_yolo(fg, tracks, fg.shape)

            cv2.imwrite(
                os.path.join(output_dir, f"bin{frame_id:06d}.bmp"),
                fg
            )

print("\n✅ ALL FRAMES PROCESSED SUCCESSFULLY!")

def load_mask(path):
    return cv2.imread(path, 0)


def compute_confusion(pred, gt):
    valid = (gt == 0) | (gt == 255)
    pred_fg = (pred == 255)
    gt_fg = (gt == 255)

    TP = np.sum(pred_fg & gt_fg & valid)
    FP = np.sum(pred_fg & ~gt_fg & valid)
    FN = np.sum(~pred_fg & gt_fg & valid)
    TN = np.sum(~pred_fg & ~gt_fg & valid)

    return TP, FP, FN, TN


def compute_metrics(TP, FP, FN, TN):
    eps = 1e-8

    precision = TP / (TP + FP + eps)
    recall = TP / (TP + FN + eps)
    fscore = 2 * precision * recall / (precision + recall + eps)
    accuracy = (TP + TN) / (TP + FP + FN + TN + eps)

    return precision, recall, fscore, accuracy

SELECTED_CATEGORIES = [
    "baseline",
    "shadow",
    "dynamicBackground",
    "cameraJitter"
]

CHALLENGING_CATEGORIES = [
    "badWeather",
    "PTZ",
    "turbulence",
    "nightVideos",
    "intermittentObjectMotion",
    "lowFramerate",
    "thermal"
]

def evaluate_categories(category_list, title):

    results = []

    for category in category_list:

        category_path = os.path.join(DATASET_ROOT, category)

        if not os.path.isdir(category_path):
            continue

        for sequence in os.listdir(category_path):

            gt_dir = os.path.join(category_path, sequence, "groundtruth")
            pred_dir = os.path.join(RESULTS_ROOT, category, sequence)

            if not os.path.isdir(gt_dir) or not os.path.isdir(pred_dir):
                continue

            TP = FP = FN = TN = 0

            for fname in os.listdir(gt_dir):

                if not fname.endswith((".png", ".bmp")):
                    continue

                gt = load_mask(os.path.join(gt_dir, fname))
                pred = load_mask(
                    os.path.join(pred_dir, f"bin{fname[2:8]}.bmp")
                )

                if gt is None or pred is None:
                    continue

                if gt.shape != pred.shape:
                    pred = cv2.resize(
                        pred,
                        (gt.shape[1], gt.shape[0]),
                        interpolation=cv2.INTER_NEAREST
                    )

                tTP, tFP, tFN, tTN = compute_confusion(pred, gt)

                TP += tTP
                FP += tFP
                FN += tFN
                TN += tTN

            p, r, f, a = compute_metrics(TP, FP, FN, TN)

            results.append({
                "Category": category,
                "Sequence": sequence,
                "Precision": p,
                "Recall": r,
                "F-score": f,
                "Accuracy": a
            })

    df = pd.DataFrame(results)

    print("\n==============================")
    print(title)
    print("==============================")
    print(df[["Precision","Recall","F-score","Accuracy"]].mean())

    return df

df_main = evaluate_categories(
    SELECTED_CATEGORIES,
    "📊 MAIN EVALUATION (Selected Categories)"
)

df_challenging = evaluate_categories(
    CHALLENGING_CATEGORIES,
    "📊 CHALLENGING SCENARIOS EVALUATION"
)









